# File: .github/workflows/frontend-ci.yml

name: Frontend App CI/CD

on:
  push:
    branches:
      - main # Sesuaikan dengan nama branch utama Anda (misalnya: master)
    paths:
      - 'ToDo-React/front-end/**' # Hanya trigger jika file di folder frontend berubah

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
  
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./ToDo-React/front-end
          push: true
          # Tag: johanagustianpohan/todo-web-app-devops:frontend-latest
          tags: ${{ env.DOCKER_USER }}/todo-web-app-devops:frontend-latest
          build-args: |
            # PENTING: Gunakan localhost:4000 agar browser (host) bisa mengakses API
            VITE_API_URL=http://localhost:4000